version: 2
updates:
  - package-ecosystem: "pip" # For Python dependencies
    directory: "/" # Location of the requirements.txt file
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker" # For Docker dependencies, if applicable
    directory: "/" # Location of the Dockerfile
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions" # For GitHub Actions dependencies, if applicable
    directory: "/" # Location of the GitHub Actions workflows
    schedule:
      interval: "weekly"
